{{- if eq .chezmoi.os "linux" }}
[".local/share/zsh/plugins/zas"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    refreshPeriod = "168h"

[".local/share/zsh/plugins/fsh"]
    type = "git-repo"
    url = "https://github.com/zdharma-continuum/fast-syntax-highlighting.git"
    refreshPeriod = "168h"
{{- end }}
