format = """
$os\
$sudo\
$directory\
$git_branch\
$git_status\
$direnv\
$cmd_duration\
$time\
$line_break\
$character"""

add_newline = true

[sudo]
disabled = false
style = 'fg:white bg:purple'
symbol = ' sudo'
format = '[](fg:purple)[ $symbol ]($style)[](fg:purple)'

[directory]
style = 'fg:white bg:blue'
format = '[](fg:blue)[  $path ]($style)[](fg:blue)'
truncation_length = 6
truncation_symbol = '…/'
truncate_to_repo = false

[git_branch]
symbol = ''
style = 'fg:black bg:green'
format = '[](fg:green)[ $symbol $branch ]($style)'

[git_status]
style = 'fg:black bg:green'
ahead = '⇡${count}'
behind = '⇣${count}'
modified = '!${count}'
format = '[$all_status$ahead_behind ]($style)[](fg:green)'

[direnv]
disabled = false
style = 'fg:black bg:yellow'
format = '[](fg:yellow)[ ▼ $allowed ]($style)[](fg:yellow)'

[time]
disabled = false
time_format = '%T'
style = 'fg:white'
format = '[ at  $time]($style)'

[cmd_duration]
style = 'fg:bright-yellow'
format = '[ took  $duration]($style)'

[os]
disabled = false
style = "bg:bright-black fg:white"
format = '[](fg:bright-black)[ $symbol ]($style)[](fg:bright-black)'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""
